baseURL = "http://example.alexander_rodriguez.com/"
title = "Alexander Rodriguez"
subtitle = "Astrophysics & Cosmology"
languageCode = "en-us"
theme = "hugo-coder"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Alexander Rodriguez"
    authorLocation="Boulder, CO"
    info = "Astrophysics & Cosmology"
    description = "John Doe's personal website"
    keywords = "Astrophysics & Cosmology"
    avatarurl = "profile-2.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/alro15260"

# Menu links
[[menu.main]]
    name = "Research"
    weight = 1
    url  = "/research/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Contact"
    weight = 3
    url = "/contact/"
[[menu.main]]
    name = "Talks"
    weight = 4
    url = "https://drive.google.com/drive/u/0/folders/1rGD6c0FPf0dt1wrxe0oOjwPKwdTR_puj"
[[menu.main]]
    name = "CV"
    weight = 5
    url = "CV.pdf"
